import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */
public class register extends javax.swing.JFrame {

    
    Connection conn = null;
    Statement stmt2 = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    int rs4;
    int rs3 ;
    
    String rollNum ;
    public int id ;
    String ids;
    public int grade;
    public String class_ ;
    
    /**
     * Creates new form register
     */
    public register() {
        super("register");
        initComponents();
        conn = dbconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RLname = new javax.swing.JLabel();
        RLemail = new javax.swing.JLabel();
        RLpassword = new javax.swing.JLabel();
        RLclass = new javax.swing.JLabel();
        RBregister = new javax.swing.JButton();
        RTname = new javax.swing.JTextField();
        RTemail = new javax.swing.JTextField();
        RTpassword = new javax.swing.JTextField();
        RTgrade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RLname.setText("Name");

        RLemail.setText("Email");

        RLpassword.setText("Password");

        RLclass.setText("Grade");

        RBregister.setText("Register");
        RBregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBregisterActionPerformed(evt);
            }
        });

        RTname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RTnameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please Enter your Details");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("1 : 20");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RLclass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RLemail)
                            .addComponent(RLpassword)
                            .addComponent(RLname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RTname)
                            .addComponent(RTemail, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(RTpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(RTgrade, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(RBregister))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RLname)
                    .addComponent(RTname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RLemail)
                    .addComponent(RTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RLpassword)
                    .addComponent(RTpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RLclass)
                    .addComponent(RTgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(RBregister)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBregisterActionPerformed
        // TODO add your handling code here:
        
        
//        Adding data initially
        try {
            
            stmt2 = conn.createStatement();
            String regEmail = RTemail.getText();
            String regPassword = RTpassword.getText();
            String regName = RTname.getText();
            int regGrade =  Integer.parseInt(RTgrade.getText()); 
            
            String sql = "INSERT INTO student (id, stdemail, stdpassword, stdname, stdgrade, stdclass) VALUES (NULL, '"+regEmail+"', '"+regPassword+"', '"+regName+"', '"+regGrade+"', NULL);";
            rs3 = stmt2.executeUpdate(sql);
            
            if (rs3 > 0){
//                setVisible(false);
                
//                home objecth = new home();
//                objecth.setVisible(true);
//                System.out.println("Added");
                System.out.println("Done adding Student initially");
                }
            else{
                JOptionPane.showMessageDialog(null, "Error adding student");
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
//        
//      Getting the incremented id and Generating the roll number
        try {
            String sql2 = "SELECT * from student WHERE stdemail = '"+RTemail.getText()+"'";

            rs2 = stmt2.executeQuery(sql2);
            
            while (rs2.next()) {
                id = rs2.getInt("id");
                grade = rs2.getInt("stdgrade");
                ids = Integer.toString(id);
                rollNum = "2022/0" + ids;
            }
            
            if ((grade >= 12) & (grade <= 14)) {
                
                class_ = "BA";
                }
            else if ((grade >= 15) & (grade <= 17)){
                class_ = "GC";
                }
            else if ((grade >= 18) & (grade <= 20)){
                class_ = "CS";
                }
            else {
                class_ = "Rejected";
                }
            
//            System.out.println(rollNum);
            
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        
//        Adding Roll Number and class
        try {
            
            stmt2 = conn.createStatement();
            
            String sql3 = "UPDATE `student` SET `stdclass` = '"+class_+"', `stdrollnumber` = '"+rollNum+"' WHERE `student`.`id` = '"+id+"';";
            
            rs4 = stmt2.executeUpdate(sql3);
            
            if (rs4 > 0){
//               
                System.out.println("Done adding roll number");
                JOptionPane.showMessageDialog(null, "Student has been added");
                
                setVisible(false);
                
                login objectl = new login();
                objectl.setVisible(true);                
                }
            else{
                JOptionPane.showMessageDialog(null, "Error adding Roll Number");
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_RBregisterActionPerformed

    private void RTnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RTnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RTnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RBregister;
    private javax.swing.JLabel RLclass;
    private javax.swing.JLabel RLemail;
    private javax.swing.JLabel RLname;
    private javax.swing.JLabel RLpassword;
    private javax.swing.JTextField RTemail;
    private javax.swing.JTextField RTgrade;
    private javax.swing.JTextField RTname;
    private javax.swing.JTextField RTpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
